title: CV | Adriane James
description:  Adriane James - CV
url: https://lonewanderer27.github.io/cv
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
