title: Resume - Adriane James
description:  Front-End Web Developer with 1 year of experience. Passionate about creating highly interactive web applications with responsive design on every device. 
  A team player but can also work independently. Values efficiency and timeliness in assigned tasks. 
url: https://lonewanderer27.github.io/resume
baseurl: ''
theme_skin: violet

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
