name: Upload Resume PDF to Release

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clone our repo
      - name: Clone our repo
        uses: actions/checkout@v4

      # Setup Webpage to PDF
      - name: Setup webpage to pdf action
        uses: misaelnieto/web_to_pdf_action@master
        with:
          webPageURL: https://lonewanderer27.github.io/resume
          outputFile: Ian_James_Resume_GA.pdf
          usePuppeteer: true
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

      # Set the date and time in GMT+8
      - name: Get Date and Time in GMT+8
        id: get_datetime
        run: |
          # Set the timezone to Asia/Manila (GMT+8)
          export TZ=Asia/Manila
          
          # Format: YYYYMMDD-HHMMSS
          TAG=$(date +"%Y%m%d-%H%M%S")
          echo "Generated Tag in GMT+8: $TAG"
          echo "::set-output name=tag::$TAG"

      # Create a new tag
      - name: Create a new tag
        run: |
            TAG=${{ steps.get_datetime.outputs.tag }}
            echo "Creating tag $TAG..."
            git tag $TAG
            git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # Upload new release using tag
      - name: Upload new release using tag
        uses: svenstaro/upload-release-action@v2
        with: 
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Ian_James_Resume_GA.pdf
          asset_name: Ian_James_Resume_GA.pdf
          overwrite: true
          tag: ${{ steps.get_datetime.outputs.tag }}